all: delegate

delegate: delegate.cc delegate.h
	g++ delegate.cc -o delegate -I/extra/Cache/fpga-zynq/rocket-chip/riscv-tools/riscv-isa-sim/riscv -I/extra/Cache/fpga-zynq/rocket-chip/riscv-tools/riscv-isa-sim/build -I/extra/Cache/fpga-zynq/rocket-chip/riscv-tools/riscv-isa-sim/softfloat -I/extra/Cache/fpga-zynq/rocket-chip/riscv-tools/riscv-isa-sim/ -I/extra/Cache/fpga-zynq/rocket-chip/riscv-tools/riscv-fesvr
